### ISSUE TITLE
test_helper invokes rubocop task

### ISSUE THREAD

**Issue by lunrfarsde** [ylosix/ylosix#5]
`test_helper.rb` invokes `rubocop` task which inspects all the code (including `vendor/bundle`), which effectively makes running any test impossible since there are 10k files.

**Comment by ryanfox1985** [comment]
Hi lunrfarsde,

thanks for your feedback, I'm using RVM https://rvm.io and bundle installs the gems in other place.

I added this folder in Rubocop ignore. Thanks.

Regards.
